version: '3'

services:
  # db:
  #   image: postgres:11.5
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: 'postgres'
  #     POSTGRES_PASSWORD: 'postgres'
  #     POSTGRES_DB: 'db_name'
  #     POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
  app:
    build: .
    # depends_on:
    #   - db
    ports:
      - 5000:5000
    tty: true
    environment:
      PYTHONPATH: '/opt/webapp/'
      PORT: '5000'
